build:
    environment:
        php: 7.0.8
    tests:
        override:
            -
                command: 'composer require --dev phpunit/phpunit && phpdbg -qrr vendor/bin/phpunit -c tests/phpunit.xml'
                coverage:
                    file: 'tests/coverage.xml'
                    format: 'php-clover'

checks:
    php: true

coding_style:
    php: {  }

filter:
    excluded_paths:
        - 'tests/*'