build:
    environment:
        php: 7.0.6
    tests:
        override:
            -
                command: 'composer require phpunit/phpunit && vendor/bin/phpunit'
                coverage:
                    file: '.reports/clover.xml'
                    format: 'php-clover'

checks:
    php: true

coding_style:
    php: {  }

filter:
    excluded_paths:
        - 'tests/*'