install:
    - composer require --dev phpunit/phpunit squizlabs/php_codesniffer

language: php

notifications:
    email: false

php:
    - '7.0'
    - nightly

script:
    - ./vendor/bin/phpunit --no-coverage
    - ./vendor/bin/phpcs --extensions=php --report-full --standard=PSR2 *.php

sudo: false
