install:
    - composer require --dev phpunit/phpunit squizlabs/php_codesniffer

language: php

notifications:
    email: false

php:
    - 7.0
    - 7.1
    - nightly

script:
    - ./vendor/bin/phpunit
    - ./vendor/bin/phpcs --extensions=php --report-full --standard=PSR2 ./src/

sudo: false
