install:
    - composer install --no-interaction --prefer-source

language: php

notifications:
    email: false

php:
    - '5.6'
    - '7.0'
    - hhvm
    - nightly

script:
    - ./bin/phpunit

sudo: false
