install:
    - composer install --no-interaction

language: php

notifications:
    email: false

php:
    - '5.6'
    - '7.0'
    - hhvm
    - nightly

script:
    - ./bin/phpunit --no-coverage

sudo: false
