<?php

namespace Tests\Currency;

use KubaWerlos\Money\Currency;
use PHPUnit_Framework_TestCase;

/**
 * @covers KubaWerlos\Money\Currency::getFractionDigits
 */
class GetFractionDigitsTest extends PHPUnit_Framework_TestCase
{
    /**
     * @dataProvider getFractionDigitsProvider
     * @param int $expectedFractionDigits
     * @param string $code
     * @test
     */
    public function getFractionDigits($expectedFractionDigits, $code)
    {
        $currency = new Currency($code);

        $actualFractionDigits = $currency->getFractionDigits();

        $this->assertSame($expectedFractionDigits, $actualFractionDigits);
    }

    /**
     * @return array
     */
    public function getFractionDigitsProvider()
    {
        return [
            [ 2, 'AED' ],
            [ 2, 'AFN' ],
            [ 2, 'ALL' ],
            [ 2, 'AMD' ],
            [ 2, 'ANG' ],
            [ 2, 'AOA' ],
            [ 2, 'ARS' ],
            [ 2, 'AUD' ],
            [ 2, 'AWG' ],
            [ 2, 'AZN' ],
            [ 2, 'BAM' ],
            [ 2, 'BBD' ],
            [ 2, 'BDT' ],
            [ 2, 'BGN' ],
            [ 3, 'BHD' ],
            [ 0, 'BIF' ],
            [ 2, 'BMD' ],
            [ 2, 'BND' ],
            [ 2, 'BOB' ],
            [ 2, 'BOV' ],
            [ 2, 'BRL' ],
            [ 2, 'BSD' ],
            [ 2, 'BTN' ],
            [ 2, 'BWP' ],
            [ 2, 'BYN' ],
            [ 0, 'BYR' ],
            [ 2, 'BZD' ],
            [ 2, 'CAD' ],
            [ 2, 'CDF' ],
            [ 2, 'CHE' ],
            [ 2, 'CHF' ],
            [ 2, 'CHW' ],
            [ 4, 'CLF' ],
            [ 0, 'CLP' ],
            [ 2, 'CNY' ],
            [ 2, 'COP' ],
            [ 2, 'COU' ],
            [ 2, 'CRC' ],
            [ 2, 'CUC' ],
            [ 2, 'CUP' ],
            [ 2, 'CVE' ],
            [ 2, 'CZK' ],
            [ 0, 'DJF' ],
            [ 2, 'DKK' ],
            [ 2, 'DOP' ],
            [ 2, 'DZD' ],
            [ 2, 'EGP' ],
            [ 2, 'ERN' ],
            [ 2, 'ETB' ],
            [ 2, 'EUR' ],
            [ 2, 'FJD' ],
            [ 2, 'FKP' ],
            [ 2, 'GBP' ],
            [ 2, 'GEL' ],
            [ 2, 'GHS' ],
            [ 2, 'GIP' ],
            [ 2, 'GMD' ],
            [ 0, 'GNF' ],
            [ 2, 'GTQ' ],
            [ 2, 'GYD' ],
            [ 2, 'HKD' ],
            [ 2, 'HNL' ],
            [ 2, 'HRK' ],
            [ 2, 'HTG' ],
            [ 2, 'HUF' ],
            [ 2, 'IDR' ],
            [ 2, 'ILS' ],
            [ 2, 'INR' ],
            [ 3, 'IQD' ],
            [ 2, 'IRR' ],
            [ 0, 'ISK' ],
            [ 2, 'JMD' ],
            [ 3, 'JOD' ],
            [ 0, 'JPY' ],
            [ 2, 'KES' ],
            [ 2, 'KGS' ],
            [ 2, 'KHR' ],
            [ 0, 'KMF' ],
            [ 2, 'KPW' ],
            [ 0, 'KRW' ],
            [ 3, 'KWD' ],
            [ 2, 'KYD' ],
            [ 2, 'KZT' ],
            [ 2, 'LAK' ],
            [ 2, 'LBP' ],
            [ 2, 'LKR' ],
            [ 2, 'LRD' ],
            [ 2, 'LSL' ],
            [ 3, 'LYD' ],
            [ 2, 'MAD' ],
            [ 2, 'MDL' ],
            [ 2, 'MGA' ],
            [ 2, 'MKD' ],
            [ 2, 'MMK' ],
            [ 2, 'MNT' ],
            [ 2, 'MOP' ],
            [ 2, 'MRO' ],
            [ 2, 'MUR' ],
            [ 2, 'MVR' ],
            [ 2, 'MWK' ],
            [ 2, 'MXN' ],
            [ 2, 'MXV' ],
            [ 2, 'MYR' ],
            [ 2, 'MZN' ],
            [ 2, 'NAD' ],
            [ 2, 'NGN' ],
            [ 2, 'NIO' ],
            [ 2, 'NOK' ],
            [ 2, 'NPR' ],
            [ 2, 'NZD' ],
            [ 3, 'OMR' ],
            [ 2, 'PAB' ],
            [ 2, 'PEN' ],
            [ 2, 'PGK' ],
            [ 2, 'PHP' ],
            [ 2, 'PKR' ],
            [ 2, 'PLN' ],
            [ 0, 'PYG' ],
            [ 2, 'QAR' ],
            [ 2, 'RON' ],
            [ 2, 'RSD' ],
            [ 2, 'RUB' ],
            [ 0, 'RWF' ],
            [ 2, 'SAR' ],
            [ 2, 'SBD' ],
            [ 2, 'SCR' ],
            [ 2, 'SDG' ],
            [ 2, 'SEK' ],
            [ 2, 'SGD' ],
            [ 2, 'SHP' ],
            [ 2, 'SLL' ],
            [ 2, 'SOS' ],
            [ 2, 'SRD' ],
            [ 2, 'SSP' ],
            [ 2, 'STD' ],
            [ 2, 'SVC' ],
            [ 2, 'SYP' ],
            [ 2, 'SZL' ],
            [ 2, 'THB' ],
            [ 2, 'TJS' ],
            [ 2, 'TMT' ],
            [ 3, 'TND' ],
            [ 2, 'TOP' ],
            [ 2, 'TRY' ],
            [ 2, 'TTD' ],
            [ 2, 'TWD' ],
            [ 2, 'TZS' ],
            [ 2, 'UAH' ],
            [ 0, 'UGX' ],
            [ 2, 'USD' ],
            [ 2, 'USN' ],
            [ 0, 'UYI' ],
            [ 2, 'UYU' ],
            [ 2, 'UZS' ],
            [ 2, 'VEF' ],
            [ 0, 'VND' ],
            [ 0, 'VUV' ],
            [ 2, 'WST' ],
            [ 0, 'XAF' ],
            [ 0, 'XAG' ],
            [ 0, 'XAU' ],
            [ 0, 'XBA' ],
            [ 0, 'XBB' ],
            [ 0, 'XBC' ],
            [ 0, 'XBD' ],
            [ 2, 'XCD' ],
            [ 0, 'XDR' ],
            [ 0, 'XOF' ],
            [ 0, 'XPD' ],
            [ 0, 'XPF' ],
            [ 0, 'XPT' ],
            [ 0, 'XSU' ],
            [ 0, 'XTS' ],
            [ 0, 'XUA' ],
            [ 0, 'XXX' ],
            [ 2, 'YER' ],
            [ 2, 'ZAR' ],
            [ 2, 'ZMW' ],
            [ 2, 'ZWL' ],
        ];
    }
}
